### ISSUE TITLE
duplicate `## 🔖 Articles` node

### ISSUE THREAD

**Issue by avelino** [omnivore-app/logseq-omnivore#119]
I don't know why, but there are some cases where the article node is duplicating

<img width="788" alt="Screenshot 2023-07-07 at 12 02 00" src="https://github.com/omnivore-app/logseq-omnivore/assets/31996/c820bca8-c7b9-42e5-ae33-c80f10b0b789">

**Comment by thiswillbeyourgithub** [comment]
Same

**Comment by yoghurtdewdew** [comment]
Same and even worse.

<img width="231" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/51f7e8a1-94ce-4237-b9fa-52b161663bc0">
<img width="294" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/4f4ef945-c309-49a6-91a7-3f840b5fb7a1">

The truth is I have deleted some `## 🔖 Articles`.  I just hope there will be no heading like `## 🔖 Articles` there.

**Comment by avelino** [comment]
I noticed that it is duplicating the title article when I close line article

<img width="773" alt="Screenshot 2023-07-18 at 14 46 56" src="https://github.com/omnivore-app/logseq-omnivore/assets/31996/4dca1baa-e7ac-4622-b3d7-244091d1df35">

**Comment by yoghurtdewdew** [comment]
Now it's like this

<img width="471" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/2f5c9cbc-756b-4230-ade3-ba7415c46ead">
https://github.com/omnivore-app/logseq-omnivore/issues/119#issuecomment-1641970877

**Comment by vinodpandey** [comment]
For me, it was fixed by clearing local storage.

**Comment by yoghurtdewdew** [comment]
It doesn't work for me. I cleared local storage but it is still growing and I must clear manually.

<img width="302" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/46318032-c0c1-4f4a-9d3e-7e0a995b0db2">

**Comment by vinodpandey** [comment]
@yoghurtdewdew Can you please try below step and let us know the results?

- upgrade logseq to latest version
- clear cache using below option in settings

<img width="889" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/230595/0bf6a224-10f7-4384-a735-1097e49419c0">

**Comment by yoghurtdewdew** [comment]
Thanks for your reply! I am using the latest version, and just tried "clear cache", it doesn't work.
Every time it in sync, then it will create new headings of `Article`.

<img width="301" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/f9024efa-d995-47c3-9ac6-01fe736a7c0b">
<img width="502" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/1ef13093-a936-4d87-94d2-d178b80ebb0a">

**Comment by yoghurtdewdew** [comment]
This is still happening 😱

<img width="413" alt="image" src="https://github.com/omnivore-app/logseq-omnivore/assets/63794438/dc626ca6-eb1e-48ea-a69b-359bea7d5a86">

**Comment by sywhb** [comment]
Sorry for the delay. I finally got time to look into this now

**Comment by sywhb** [comment]
Hey @avelino @yoghurtdewdew , I have found the bug that sometimes `collapse::true/false` will be added to the heading block after syncing or explanding/collapsing it which caused the datascript query to match the `## Articles` heading to fail and create duplicate heading blocks.

I will modify the datascript to better match the heading block

**Comment by sywhb** [comment]
Hey @avelino @yoghurtdewdew , `v1.13.4` is released to address this issue.

Please kindly delete all the duplicate heading blocks or delete this whole page in Logseq and resync with Omnivore.

Please let me know if it works.

Thank you!

**Comment by yoghurtdewdew** [comment]
@sywhb Thanks a lot! 
I found that after I changed the single page name from `Omnivore` to `omnivore-saved`, the duplication of `## Articles` stopped.
Hope that could be useful to the syncing fix.
