### ISSUE TITLE
Block Reference lost after resync 

### ISSUE THREAD

**Issue by cleanclothes-pi** [omnivore-app/logseq-omnivore#43]
When I create a block reference to the synced article (in Omnivore page) in another page, then re-sync the plug-in, the referenced block is lost. This makes it impossible to reference the highlighted quotes.

I should note that my plug-in setting for "Order of Highlights" is set to "the location of highlighst in the article."

**Comment by jacksonh** [comment]
Thanks, I guess this is because we remove and re-insert. Maybe we should look into the upsert method, or just only append new nodes.

**Comment by sywhb** [comment]
#48

**Comment by sywhb** [comment]
Hey @cleanclothes-pi @YU000jp, we released a new version https://github.com/omnivore-app/logseq-omnivore/releases/tag/v1.9.0 to address this issue. Please try it and let me know if there should be any further issues.

Thank you!

**Comment by sywhb** [comment]
Avoid escaping Markdown characters in the title and highlight which caused the fetching failure.
#50

**Comment by cleanclothes-pi** [comment]
@sywhb Thank you so much! As far as my use case goes, it works great now. The reference blocks and quotes are not lost anymore.

I also appreciate that the new comments are appended as new block now instead of replacing the existing one, which means I can add new comments for each highlight directino in Logseq without worry that it will be overwritten by new sync.

**Comment by YU000jp** [comment]
When I rewrote the labels and archived, no reference errors occurred.

I can now place web clips on my journal timeline. I get more references to that web clip and reuse them.

you still have another issue, but thank you for your efforts in resolving this issue.
